language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      # dependencies needed to build kcov.
      # TODO Remove when kcov v34 is available.
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

      # dependencies of the code coverage tool.
      - jq

install:
  # needed for rustfmt
  # TODO Remove when all features used in `.rustfmt.toml` are stable.
  - rustup toolchain install nightly
  - rustup component add --toolchain nightly rustfmt-preview

script:
  - travis_wait ./tools/check.sh

# TODO Do not build kcov when v34 is available, just install it directly.
after_success:
  test $TRAVIS_OS_NAME = linux
  && test $TRAVIS_RUST_VERSION = stable
  && wget https://github.com/SimonKagstrom/kcov/archive/v34.tar.gz
  && tar xzf v34.tar.gz
  && cd kcov-34
  && mkdir build
  && cd build
  && cmake ..
  && make
  && sudo make install
  && cd ../../
  && rm -rf kcov-34 v34.tar.gz
  && travis_wait ./tools/codecov.sh
  && bash <(curl -s https://codecov.io/bash)
