language: rust
dist: xenial

os:
  - linux
  - osx
  - windows

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

install:
  - rustup component add rustfmt
  - cargo install cargo-deadlinks

script:
  - ./tools/check.sh

after_success:
  test "$TRAVIS_OS_NAME" = linux
  && test "$TRAVIS_RUST_VERSION" = stable
  && sudo apt-get update
  && sudo apt-get install libssl-dev pkg-config cmake zlib1g-dev
  && cargo install cargo-tarpaulin
  && travis_wait ./tools/codecov.sh --xml
  && bash <(curl -s https://codecov.io/bash)
